name: PR Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"   # runs on all branches for PRs

jobs:
  lint:
    name: Ruff Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Run Ruff check
        run: uv run ruff check supra_sdk tests/unit examples --no-fix
